apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: papermake
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - server-deployment.yaml
  - server-service.yaml
  - render-worker-deployment.yaml
  - maintenance-worker-deployment.yaml
images:
  - name: papermake-server
    newName: papermake-server
    newTag: latest
  - name: papermake-worker
    newName: papermake-worker
    newTag: latest
