apiVersion: v1
kind: Service
metadata:
  name: papermake-server
  namespace: papermake
  labels:
    app.kubernetes.io/name: papermake
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: papermake
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 80
      targetPort: http
